-- V11 Stage 4: thread, turn, thread_item, thread_event, goal, thread_relation (S04-C01)
CREATE TABLE `V11Thread` (
  `id` varchar(36) NOT NULL,
  `tenantId` varchar(36) NOT NULL,
  `ownerUserId` varchar(36) NOT NULL,
  `primaryAgentId` varchar(36) NOT NULL,
  `defaultWorkspaceId` varchar(36) NULL,
  `activeGoalId` varchar(36) NULL,
  `title` text NULL,
  `defaultModelRef` varchar(256) NULL,
  `defaultEnvironmentDefinitionId` varchar(36) NULL,
  `lifecycleState` enum('active','archived','deleted') NOT NULL DEFAULT 'active',
  `lastActivityAt` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `lastTurnSequence` bigint NOT NULL DEFAULT 0,
  `lastItemSequence` bigint NOT NULL DEFAULT 0,
  `lastEventSequence` bigint NOT NULL DEFAULT 0,
  `pendingQueueVersionNo` bigint NOT NULL DEFAULT 1,
  `versionNo` bigint NOT NULL DEFAULT 1,
  `createdAt` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updatedAt` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `deletedAt` datetime(3) NULL,
  PRIMARY KEY(`id`),
  KEY `V11Thread_tenant_owner_lifecycle_activity_idx`(`tenantId`,`ownerUserId`,`lifecycleState`,`lastActivityAt`),
  KEY `V11Thread_tenant_agent_activity_idx`(`tenantId`,`primaryAgentId`,`lastActivityAt`),
  CONSTRAINT `V11Thread_tenantId_fk` FOREIGN KEY (`tenantId`) REFERENCES `Tenant`(`id`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB;--> statement-breakpoint
CREATE TABLE `V11Turn` (
  `id` varchar(36) NOT NULL,
  `threadId` varchar(36) NOT NULL,
  `turnSequence` bigint NOT NULL,
  `triggerType` enum('user_message','thread_schedule','thread_webhook','job_result_projection','system') NOT NULL,
  `triggerRef` varchar(256) NULL,
  `triggerItemId` varchar(36) NULL,
  `turnState` enum('accepted','queued','running','waiting_user','regenerating','completed','interrupted','failed','cancelled') NOT NULL DEFAULT 'accepted',
  `activeInvocationId` varchar(36) NULL,
  `latestInvocationId` varchar(36) NULL,
  `adoptedInvocationId` varchar(36) NULL,
  `finalItemId` varchar(36) NULL,
  `errorCode` varchar(128) NULL,
  `regenerationNo` bigint NOT NULL DEFAULT 0,
  `regenerationBaseState` enum('completed','interrupted','failed') NULL,
  `acceptedAt` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `startedAt` datetime(3) NULL,
  `waitingAt` datetime(3) NULL,
  `finishedAt` datetime(3) NULL,
  `versionNo` bigint NOT NULL DEFAULT 1,
  PRIMARY KEY(`id`),
  UNIQUE KEY `V11Turn_thread_sequence_uq`(`threadId`,`turnSequence`),
  KEY `V11Turn_thread_state_accepted_idx`(`threadId`,`turnState`,`acceptedAt`),
  CONSTRAINT `V11Turn_threadId_fk` FOREIGN KEY (`threadId`) REFERENCES `V11Thread`(`id`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB;--> statement-breakpoint
CREATE TABLE `V11ThreadItem` (
  `id` varchar(36) NOT NULL,
  `threadId` varchar(36) NOT NULL,
  `turnId` varchar(36) NOT NULL,
  `itemSequence` bigint NOT NULL,
  `itemType` enum('user_message','user_guidance','agent_message','tool_call','artifact','job_result','child_thread','user_action') NOT NULL,
  `itemState` enum('pending','completed','failed','superseded','cancelled') NOT NULL DEFAULT 'pending',
  `authorType` enum('user','agent','system','tool') NOT NULL,
  `authorId` varchar(36) NULL,
  `contentJson` json NOT NULL,
  `contentHash` varchar(128) NOT NULL,
  `contextPolicy` enum('include','summary_only','exclude','sensitive') NOT NULL DEFAULT 'include',
  `invocationId` varchar(36) NULL,
  `supersededByItemId` varchar(36) NULL,
  `createdAt` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updatedAt` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  PRIMARY KEY(`id`),
  UNIQUE KEY `V11ThreadItem_thread_sequence_uq`(`threadId`,`itemSequence`),
  KEY `V11ThreadItem_thread_turn_sequence_idx`(`threadId`,`turnId`,`itemSequence`),
  KEY `V11ThreadItem_invocation_idx`(`invocationId`),
  CONSTRAINT `V11ThreadItem_threadId_fk` FOREIGN KEY (`threadId`) REFERENCES `V11Thread`(`id`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB;--> statement-breakpoint
CREATE TABLE `V11ThreadEvent` (
  `id` varchar(36) NOT NULL,
  `threadId` varchar(36) NOT NULL,
  `eventSequence` bigint NOT NULL,
  `eventType` varchar(128) NOT NULL,
  `schemaVersion` int NOT NULL DEFAULT 1,
  `turnId` varchar(36) NULL,
  `itemId` varchar(36) NULL,
  `invocationId` varchar(36) NULL,
  `actorType` enum('user','agent','system','tool','service') NOT NULL,
  `actorId` varchar(36) NULL,
  `payloadJson` json NOT NULL,
  `correlationId` varchar(36) NULL,
  `causationId` varchar(36) NULL,
  `idempotencyKey` varchar(128) NULL,
  `occurredAt` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `ingestedAt` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  PRIMARY KEY(`id`),
  UNIQUE KEY `V11ThreadEvent_thread_sequence_uq`(`threadId`,`eventSequence`),
  UNIQUE KEY `V11ThreadEvent_thread_idempotency_uq`(`threadId`,`idempotencyKey`),
  KEY `V11ThreadEvent_thread_occurred_id_idx`(`threadId`,`occurredAt`,`id`),
  KEY `V11ThreadEvent_turn_sequence_idx`(`turnId`,`eventSequence`),
  KEY `V11ThreadEvent_invocation_sequence_idx`(`invocationId`,`eventSequence`),
  CONSTRAINT `V11ThreadEvent_threadId_fk` FOREIGN KEY (`threadId`) REFERENCES `V11Thread`(`id`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB;--> statement-breakpoint
CREATE TABLE `V11Goal` (
  `id` varchar(36) NOT NULL,
  `threadId` varchar(36) NOT NULL,
  `objective` text NOT NULL,
  `successCriteriaJson` json NOT NULL,
  `constraintsJson` json NULL,
  `currentStateJson` json NULL,
  `goalState` enum('active','blocked','completed','cancelled') NOT NULL DEFAULT 'active',
  `createdBy` varchar(128) NOT NULL,
  `createdAt` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updatedAt` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `completedAt` datetime(3) NULL,
  PRIMARY KEY(`id`),
  KEY `V11Goal_thread_state_idx`(`threadId`,`goalState`),
  CONSTRAINT `V11Goal_threadId_fk` FOREIGN KEY (`threadId`) REFERENCES `V11Thread`(`id`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB;--> statement-breakpoint
CREATE TABLE `V11ThreadRelation` (
  `id` varchar(36) NOT NULL,
  `parentThreadId` varchar(36) NOT NULL,
  `childThreadId` varchar(36) NOT NULL,
  `relationType` enum('delegate','fork','workflow_child') NOT NULL,
  `sourceTurnId` varchar(36) NULL,
  `sourceItemId` varchar(36) NULL,
  `sourceInvocationId` varchar(36) NULL,
  `targetAgentId` varchar(36) NULL,
  `taskPayloadRef` varchar(512) NULL,
  `taskPayloadHash` varchar(128) NULL,
  `contextTransferPolicyJson` json NULL,
  `budgetPolicyJson` json NULL,
  `relationState` enum('creating','active','cancel_requested','completed','failed','cancelled') NOT NULL DEFAULT 'creating',
  `itemId` varchar(36) NULL,
  `resultItemId` varchar(36) NULL,
  `resultRef` varchar(512) NULL,
  `resultHash` varchar(128) NULL,
  `createdAt` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `completedAt` datetime(3) NULL,
  PRIMARY KEY(`id`),
  UNIQUE KEY `V11ThreadRelation_parent_child_type_uq`(`parentThreadId`,`childThreadId`,`relationType`),
  KEY `V11ThreadRelation_parent_state_idx`(`parentThreadId`,`relationState`),
  KEY `V11ThreadRelation_child_idx`(`childThreadId`),
  CONSTRAINT `V11ThreadRelation_parentThreadId_fk` FOREIGN KEY (`parentThreadId`) REFERENCES `V11Thread`(`id`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `V11ThreadRelation_childThreadId_fk` FOREIGN KEY (`childThreadId`) REFERENCES `V11Thread`(`id`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB;
