-- V11 Stage 4: projection_checkpoint, event_delivery_failure, event_stream_floor, thread_list_projection, turn_timeline_projection (S04-C02)
CREATE TABLE `V11ProjectionCheckpoint` (
  `consumerName` varchar(128) NOT NULL,
  `streamType` enum('thread_event','job_event') NOT NULL,
  `shardKey` varchar(36) NOT NULL,
  `lastSequence` bigint NOT NULL DEFAULT 0,
  `lastEventId` varchar(36) NULL,
  `updatedAt` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `versionNo` bigint NOT NULL DEFAULT 1,
  PRIMARY KEY(`consumerName`,`streamType`,`shardKey`)
) ENGINE=InnoDB;--> statement-breakpoint
CREATE TABLE `V11EventDeliveryFailure` (
  `id` varchar(36) NOT NULL,
  `consumerName` varchar(128) NOT NULL,
  `streamType` enum('thread_event','job_event') NOT NULL,
  `streamId` varchar(36) NOT NULL,
  `eventId` varchar(36) NOT NULL,
  `eventSequence` bigint NOT NULL,
  `payloadHash` varchar(128) NULL,
  `failureClass` varchar(64) NOT NULL,
  `failureState` enum('retrying','quarantined','resolved') NOT NULL DEFAULT 'retrying',
  `attemptCount` int NOT NULL DEFAULT 0,
  `nextRetryAt` datetime(3) NULL,
  `lastErrorCode` varchar(128) NULL,
  `lastErrorDetailJson` json NULL,
  `createdAt` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updatedAt` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `resolvedAt` datetime(3) NULL,
  PRIMARY KEY(`id`),
  UNIQUE KEY `V11EventDeliveryFailure_consumer_stream_event_uq`(`consumerName`,`streamType`,`streamId`,`eventId`),
  KEY `V11EventDeliveryFailure_consumer_stream_sequence_idx`(`consumerName`,`streamType`,`streamId`,`eventSequence`),
  KEY `V11EventDeliveryFailure_state_retry_idx`(`failureState`,`nextRetryAt`)
) ENGINE=InnoDB;--> statement-breakpoint
CREATE TABLE `V11EventStreamFloor` (
  `streamType` enum('thread_event','job_event') NOT NULL,
  `streamId` varchar(36) NOT NULL,
  `tenantId` varchar(36) NOT NULL,
  `earliestAvailableSequence` bigint NOT NULL DEFAULT 1,
  `latestSequence` bigint NOT NULL DEFAULT 0,
  `updatedAt` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  PRIMARY KEY(`streamType`,`streamId`),
  KEY `V11EventStreamFloor_tenant_idx`(`tenantId`)
) ENGINE=InnoDB;--> statement-breakpoint
CREATE TABLE `V11ThreadListProjection` (
  `threadId` varchar(36) NOT NULL,
  `tenantId` varchar(36) NOT NULL,
  `ownerUserId` varchar(36) NOT NULL,
  `primaryAgentId` varchar(36) NOT NULL,
  `title` text NULL,
  `lifecycleState` varchar(32) NOT NULL DEFAULT 'active',
  `lastActivityAt` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `lastItemSummary` text NULL,
  `lastItemType` varchar(32) NULL,
  `lastItemSequence` bigint NULL,
  `lastItemAuthorType` varchar(32) NULL,
  `lastItemCreatedAt` datetime(3) NULL,
  `currentTurnId` varchar(36) NULL,
  `currentTurnSequence` bigint NULL,
  `currentTurnState` varchar(32) NULL,
  `latestEventSequence` bigint NOT NULL DEFAULT 0,
  `latestEventId` varchar(36) NULL,
  `hasUnreadEvents` int NOT NULL DEFAULT 0,
  `updatedAt` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `versionNo` bigint NOT NULL DEFAULT 1,
  PRIMARY KEY(`threadId`),
  KEY `V11ThreadListProjection_tenant_owner_activity_idx`(`tenantId`,`ownerUserId`,`lastActivityAt`),
  KEY `V11ThreadListProjection_tenant_agent_activity_idx`(`tenantId`,`primaryAgentId`,`lastActivityAt`),
  KEY `V11ThreadListProjection_tenant_lifecycle_idx`(`tenantId`,`lifecycleState`),
  CONSTRAINT `V11ThreadListProjection_tenantId_fk` FOREIGN KEY (`tenantId`) REFERENCES `Tenant`(`id`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB;--> statement-breakpoint
CREATE TABLE `V11TurnTimelineProjection` (
  `turnId` varchar(36) NOT NULL,
  `threadId` varchar(36) NOT NULL,
  `tenantId` varchar(36) NOT NULL,
  `turnSequence` bigint NOT NULL,
  `turnState` varchar(32) NOT NULL DEFAULT 'accepted',
  `triggerType` varchar(32) NOT NULL,
  `triggerItemId` varchar(36) NULL,
  `triggerItemType` varchar(32) NULL,
  `triggerItemSummary` text NULL,
  `triggerItemCreatedAt` datetime(3) NULL,
  `finalItemId` varchar(36) NULL,
  `finalItemType` varchar(32) NULL,
  `finalItemSummary` text NULL,
  `finalItemCreatedAt` datetime(3) NULL,
  `itemCount` int NOT NULL DEFAULT 0,
  `lastItemSummary` text NULL,
  `lastItemType` varchar(32) NULL,
  `lastItemSequence` bigint NULL,
  `lastItemCreatedAt` datetime(3) NULL,
  `acceptedAt` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `startedAt` datetime(3) NULL,
  `waitingAt` datetime(3) NULL,
  `finishedAt` datetime(3) NULL,
  `errorCode` varchar(128) NULL,
  `regenerationNo` bigint NOT NULL DEFAULT 0,
  `latestEventSequence` bigint NOT NULL DEFAULT 0,
  `updatedAt` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `versionNo` bigint NOT NULL DEFAULT 1,
  PRIMARY KEY(`turnId`),
  UNIQUE KEY `V11TurnTimelineProjection_thread_sequence_uq`(`threadId`,`turnSequence`),
  KEY `V11TurnTimelineProjection_tenant_thread_sequence_idx`(`tenantId`,`threadId`,`turnSequence`),
  KEY `V11TurnTimelineProjection_thread_state_idx`(`threadId`,`turnState`),
  CONSTRAINT `V11TurnTimelineProjection_tenantId_fk` FOREIGN KEY (`tenantId`) REFERENCES `Tenant`(`id`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB;
