CREATE TABLE IF NOT EXISTS `RouteEligibilityProjection` (
  `routeId` varchar(36) NOT NULL,
  `tenantId` varchar(36) NOT NULL,
  `agentId` varchar(36) NOT NULL,
  `routeSetId` varchar(36) NOT NULL,
  `routeScopeKey` varchar(128) NOT NULL,
  `routeSetVersionNo` bigint unsigned NOT NULL,
  `routeRevisionId` varchar(36) NOT NULL,
  `routeRevisionNo` bigint unsigned NOT NULL,
  `routeActivationId` varchar(36) NOT NULL,
  `routeActivationSequence` bigint unsigned NOT NULL,
  `routeGroupId` varchar(128) NOT NULL,
  `selectorDigest` varchar(71) NOT NULL,
  `eligibilityConditionsJson` json NOT NULL,
  `specificity` int NOT NULL,
  `priorityNo` int NOT NULL,
  `trafficWeight` int NOT NULL,
  `effectiveFrom` datetime(3),
  `effectiveUntil` datetime(3),
  `agentRevisionId` varchar(36) NOT NULL,
  `agentRevisionState` varchar(32) NOT NULL,
  `agentLifecycleState` varchar(32) NOT NULL,
  `agentPublicationActive` int NOT NULL,
  `agentEvidenceValid` int NOT NULL,
  `runtimeRevisionId` varchar(36) NOT NULL,
  `runtimeRevisionState` varchar(32) NOT NULL,
  `runtimeLifecycleState` varchar(32) NOT NULL,
  `runtimePublicationActive` int NOT NULL,
  `runtimeEvidenceValid` int NOT NULL,
  `runtimeConformanceValid` int NOT NULL,
  `policyRevisionId` varchar(36),
  `policyRevisionState` varchar(32),
  `capabilityCompatibilityDigest` varchar(71) NOT NULL,
  `agentArtifactDigest` varchar(71),
  `runtimeArtifactDigest` varchar(71),
  `runtimeConfigDigest` varchar(71),
  `routeContentDigest` varchar(71) NOT NULL,
  `eligibilityState` enum('eligible','ineligible','pending_rebuild') NOT NULL,
  `projectionVersionNo` bigint unsigned NOT NULL,
  `lastRebuiltAt` datetime(3) NOT NULL,
  PRIMARY KEY (`routeId`),
  UNIQUE INDEX `RouteEligibilityProjection_revision_activation_uq` (`routeRevisionId`, `routeActivationId`),
  INDEX `RouteEligibilityProjection_tenant_agent_scope_idx` (`tenantId`, `agentId`, `routeScopeKey`, `eligibilityState`),
  INDEX `RouteEligibilityProjection_routeSet_version_idx` (`routeSetId`, `routeSetVersionNo`),
  INDEX `RouteEligibilityProjection_group_selector_priority_idx` (`routeGroupId`, `selectorDigest`, `priorityNo`),
  INDEX `RouteEligibilityProjection_tenant_idx` (`tenantId`)
) DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
