import { readFileSync } from "node:fs";
import { join } from "node:path";
import { describe, expect, it } from "vitest";

const CONTRACTS = [
  ["agents.ts", "/admin/api/v1/agents", "app/admin/api/v1/agents/route.ts", "GET"],
  [
    "agents.ts",
    "/admin/api/v1/agents/${agentId}",
    "app/admin/api/v1/agents/[agent_id]/route.ts",
    "GET",
  ],
  [
    "agents.ts",
    "/admin/api/v1/agents/${agentId}/revisions",
    "app/admin/api/v1/agents/[agent_id]/revisions/route.ts",
    "GET",
  ],
  [
    "agents.ts",
    "/admin/api/v1/agent-revisions/${revisionId}",
    "app/admin/api/v1/agent-revisions/[revision_id]/route.ts",
    "GET",
  ],
  [
    "agents.ts",
    "/admin/api/v1/agents/${agentId}/revisions",
    "app/admin/api/v1/agents/[agent_id]/revisions/route.ts",
    "POST",
  ],
  [
    "agents.ts",
    "/admin/api/v1/agent-revisions/${revisionId}/publish",
    "app/admin/api/v1/agent-revisions/[revision_id]/publish/route.ts",
    "POST",
  ],
  [
    "agents.ts",
    "/admin/api/v1/agent-revisions/${revisionId}/withdraw",
    "app/admin/api/v1/agent-revisions/[revision_id]/withdraw/route.ts",
    "POST",
  ],
  [
    "artifacts.ts",
    "/admin/api/v1/artifact-attestations",
    "app/admin/api/v1/artifact-attestations/route.ts",
    "GET",
  ],
  [
    "artifacts.ts",
    "/admin/api/v1/artifact-attestations/${attestationId}",
    "app/admin/api/v1/artifact-attestations/[attestation_id]/route.ts",
    "GET",
  ],
  [
    "artifacts.ts",
    "/admin/api/v1/artifact-attestations/verify",
    "app/admin/api/v1/artifact-attestations/verify/route.ts",
    "POST",
  ],
  [
    "artifacts.ts",
    "/admin/api/v1/artifact-attestations/${attestationId}/revoke",
    "app/admin/api/v1/artifact-attestations/[attestation_id]/revoke/route.ts",
    "POST",
  ],
  [
    "executions.ts",
    "/admin/api/v1/invocations/${invocationId}/execution-binding",
    "app/admin/api/v1/invocations/[invocation_id]/execution-binding/route.ts",
    "GET",
  ],
  [
    "provisioning.ts",
    "/admin/api/v1/hosted-provisioning",
    "app/admin/api/v1/hosted-provisioning/route.ts",
    "POST",
  ],
  [
    "provisioning.ts",
    "/admin/api/v1/hosted-provisioning/${requestId}",
    "app/admin/api/v1/hosted-provisioning/[request_id]/route.ts",
    "GET",
  ],
  [
    "publications.ts",
    "/admin/api/v1/publications?",
    "app/admin/api/v1/publications/route.ts",
    "GET",
  ],
  [
    "publications.ts",
    "/admin/api/v1/publications/${recordId}",
    "app/admin/api/v1/publications/[record_id]/route.ts",
    "GET",
  ],
  ["publications.ts", "/admin/api/v1/withdrawals?", "app/admin/api/v1/withdrawals/route.ts", "GET"],
  [
    "publications.ts",
    "/admin/api/v1/withdrawals/${recordId}",
    "app/admin/api/v1/withdrawals/[record_id]/route.ts",
    "GET",
  ],
  [
    "routes.ts",
    "/admin/api/v1/deployment-route-sets/${routeSetId}",
    "app/admin/api/v1/deployment-route-sets/[route_set_id]/route.ts",
    "GET",
  ],
  [
    "routes.ts",
    "/admin/api/v1/deployment-route-sets/${routeSetId}/routes",
    "app/admin/api/v1/deployment-route-sets/[route_set_id]/routes/route.ts",
    "GET",
  ],
  [
    "routes.ts",
    "/admin/api/v1/deployment-routes/${routeId}",
    "app/admin/api/v1/deployment-routes/[route_id]/route.ts",
    "GET",
  ],
  [
    "routes.ts",
    "/admin/api/v1/deployment-route-sets/${routeSetId}/activation",
    "app/admin/api/v1/deployment-route-sets/[route_set_id]/activation/route.ts",
    "PUT",
  ],
  [
    "routes.ts",
    "/admin/api/v1/deployment-routes/${routeId}/disable",
    "app/admin/api/v1/deployment-routes/[route_id]/disable/route.ts",
    "POST",
  ],
  [
    "routes.ts",
    "/admin/api/v1/deployment-route-sets",
    "app/admin/api/v1/deployment-route-sets/route.ts",
    "POST",
  ],
  ["runtimes.ts", "/admin/api/v1/runtimes", "app/admin/api/v1/runtimes/route.ts", "GET"],
  [
    "runtimes.ts",
    "/admin/api/v1/runtimes/${runtimeId}",
    "app/admin/api/v1/runtimes/[runtime_id]/route.ts",
    "GET",
  ],
  [
    "runtimes.ts",
    "/admin/api/v1/runtimes/${runtimeId}/revisions",
    "app/admin/api/v1/runtimes/[runtime_id]/revisions/route.ts",
    "GET",
  ],
  [
    "runtimes.ts",
    "/admin/api/v1/runtime-revisions/${revisionId}",
    "app/admin/api/v1/runtime-revisions/[revision_id]/route.ts",
    "GET",
  ],
  [
    "runtimes.ts",
    "/admin/api/v1/runtime-revisions/${revisionId}/publish",
    "app/admin/api/v1/runtime-revisions/[revision_id]/publish/route.ts",
    "POST",
  ],
  [
    "runtimes.ts",
    "/admin/api/v1/runtime-revisions/${revisionId}/withdraw",
    "app/admin/api/v1/runtime-revisions/[revision_id]/withdraw/route.ts",
    "POST",
  ],
  [
    "runtimes.ts",
    "/admin/api/v1/runtime-revisions/${revisionId}/conformance",
    "app/admin/api/v1/runtime-revisions/[revision_id]/conformance/route.ts",
    "POST",
  ],
  [
    "runtimes.ts",
    "/admin/api/v1/conformance-runs/${runId}",
    "app/admin/api/v1/conformance-runs/[run_id]/route.ts",
    "GET",
  ],
] as const;

describe("control plane client route contract", () => {
  it.each(CONTRACTS)("%s 的 %s 存在真实 %s %s handler", (api, path, route, method) => {
    const apiSource = readFileSync(
      join(process.cwd(), "lib/control-plane-client/api", api),
      "utf8",
    );
    const routeSource = readFileSync(join(process.cwd(), route), "utf8");
    expect(apiSource).toContain(path);
    expect(routeSource).toMatch(new RegExp(`export\\s+async\\s+function\\s+${method}\\b`));
  });
});
