import { assertSafeGitRemoteUrl } from "@/lib/external/url-safety";
import {
  ensureRemote,
  gitAdd,
  gitBranch,
  gitCommit,
  gitPush,
  gitStatus,
  withGitTimeout,
} from "@/lib/git/ops";
import { workspaceRoot } from "@/lib/workspace";
import { simpleGit } from "simple-git";

export type GitDeliverResult = {
  ok: boolean;
  pushed?: boolean;
  commit?: string;
  message?: string;
};

/**
 * 从 remoteUrl 提取 token 并剥离，返回 cleanUrl + token。
 * 如 https://x-access-token:TOKEN@host/... → { cleanUrl: https://host/..., token: TOKEN }
 */
function extractToken(remoteUrl: string): { cleanUrl: string; token: string | null } {
  const m = remoteUrl.match(/^https?:\/\/([^:]+):([^@]+)@(.+)$/);
  if (!m) return { cleanUrl: remoteUrl, token: null };
  return { cleanUrl: `https://${m[3]}`, token: m[2] ?? null };
}

/**
 * Git 交付：把会话工作区（生成的项目）init / commit / push 到用户指定的远程仓库。
 *
 * token 不落 .git/config。原 ensureRemote 写含 token 的 URL 到 .git/config。
 * 现剥离 token，ensureRemote 写 cleanUrl，push 时用 -c http.extraHeader 注入 Authorization。
 */
export async function deliverToGit(
  threadId: string,
  remoteUrl: string,
  options?: { commitMessage?: string; branch?: string; force?: boolean },
): Promise<GitDeliverResult> {
  const branch = options?.branch ?? "main";
  const commitMessage = options?.commitMessage ?? "Generated by SnowHarness";
  // P0-2:remoteUrl 协议/host 守卫,挡 file:/// / 内网 / 元数据(SSRF + 宿主文件系统写入)。
  assertSafeGitRemoteUrl(remoteUrl);
  const { cleanUrl, token } = extractToken(remoteUrl);

  try {
    await gitAdd(threadId);
    const commitRes = await gitCommit(threadId, commitMessage);
    const commit = commitRes.commitSha ?? "";

    const status = await gitStatus(threadId);
    if (status.current !== branch) {
      await gitBranch(threadId, branch);
    }

    // ensureRemote 写 cleanUrl（无 token，不落 .git/config）
    await ensureRemote(threadId, "origin", cleanUrl);

    // 有 token 时用 -c http.extraHeader 注入（不持久化到 .git/config）
    if (token) {
      const g = simpleGit({ baseDir: workspaceRoot(threadId) });
      const args = [
        "-c",
        `http.extraHeader=Authorization: token ${token}`,
        "push",
        "--set-upstream",
        "origin",
        branch,
      ];
      if (options?.force) args.push("--force");
      await withGitTimeout(g.raw(args));
    } else {
      await gitPush(threadId, { remote: "origin", branch, force: options?.force });
    }

    return { ok: true, pushed: true, commit, message: `已推送到 ${branch} 分支` };
  } catch (error) {
    return { ok: false, message: (error as Error).message };
  }
}
