import { execFileSync } from "node:child_process";
import { mkdirSync, mkdtempSync, rmSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { afterEach, beforeEach, describe, expect, it, vi } from "vitest";

/**
 * V3.7 Stage A：deliverToGit 重构零回归对照测试（plan §5 命门）。
 *
 * 重构前先固化契约：同 input 产同 commit/push 序列——以真实 bare 本地 remote 为对照，
 * 断言 GitDeliverResult 与远程落地结果。重构为复用 ops 原语后本测试仍须通过。
 * 只 mock workspaceRoot 路径解析器；simple-git 跑真实 git。deliverToGit 不触 DB。
 */

const tmp = vi.hoisted(() => ({ root: "" }));
vi.mock("@/lib/workspace", () => ({
  workspaceRoot: (threadId: string) => join(tmp.root, threadId),
}));
// 测试用 file:// 本地 bare remote(真实 git),放行 url-safety 守卫(生产仍拦 file:// 防 SSRF)
vi.mock("@/lib/external/url-safety", () => ({
  assertSafeGitRemoteUrl: vi.fn(),
  isSafeGitRemoteUrl: () => true,
  assertSafeExternalUrl: vi.fn(),
  isInternalHost: () => false,
}));

import { deliverToGit } from "@/lib/git/deliver";
import type { GitDeliverResult } from "@/lib/git/deliver";

const TID = "deliver-thread";
function ws(): string {
  return join(tmp.root, TID);
}
function gitCli(args: string[]): string {
  return execFileSync("git", args, { cwd: ws(), encoding: "utf8" }).trim();
}
function remoteRef(remotePath: string, ref: string): string {
  return execFileSync("git", ["--git-dir", remotePath, "rev-parse", ref], {
    encoding: "utf8",
  }).trim();
}

let remotePath: string;

beforeEach(() => {
  tmp.root = mkdtempSync(join(tmpdir(), "snow-git-deliver-"));
  mkdirSync(ws(), { recursive: true });
  remotePath = mkdtempSync(join(tmpdir(), "snow-git-deliver-remote-"));
  execFileSync("git", ["init", "--bare", remotePath]);
});

afterEach(() => {
  rmSync(tmp.root, { recursive: true, force: true });
  rmSync(remotePath, { recursive: true, force: true });
});

describe("deliverToGit 重构零回归（对照契约）", () => {
  it("init + commit + 推 main：result.ok + 远程 refs/heads/main 落地", async () => {
    writeFileSync(join(ws(), "index.html"), "<h1>hi</h1>");

    const result: GitDeliverResult = await deliverToGit(TID, remotePath, {
      commitMessage: "Generated by SnowHarness",
      branch: "main",
    });

    // GitDeliverResult 契约不变
    expect(result.ok).toBe(true);
    expect(result.pushed).toBe(true);
    expect(result.commit).toMatch(/^[0-9a-f]{40}$/);
    expect(result.message).toBe("已推送到 main 分支");

    // 远程 main 指向同一 commit
    expect(remoteRef(remotePath, "main")).toBe(result.commit);
    // 远程 commit message
    expect(
      execFileSync("git", ["--git-dir", remotePath, "log", "-1", "--format=%B", "main"], {
        encoding: "utf8",
      }).trim(),
    ).toBe("Generated by SnowHarness");
  });

  it("默认 commitMessage / branch（未传 options）", async () => {
    writeFileSync(join(ws(), "a.txt"), "x");
    const result = await deliverToGit(TID, remotePath);
    expect(result.ok).toBe(true);
    expect(result.message).toBe("已推送到 main 分支");
    expect(remoteRef(remotePath, "main")).toBe(result.commit);
  });

  it("自定义 branch：推到指定分支", async () => {
    writeFileSync(join(ws(), "a.txt"), "x");
    const result = await deliverToGit(TID, remotePath, { branch: "feature" });
    expect(result.ok).toBe(true);
    expect(result.message).toBe("已推送到 feature 分支");
    expect(remoteRef(remotePath, "feature")).toBe(result.commit);
  });

  it("无改动（空工作区 + 无 commit）：push 失败 → result.ok=false（不抛出）", async () => {
    // 空 repo，无任何改动可 commit；push 无 ref 可推，git 报错 → catch 返回 ok:false
    const result = await deliverToGit(TID, remotePath, { branch: "main" });
    expect(result.ok).toBe(false);
    expect(result.message).toBeTruthy();
  });

  it("再次交付（远程已存在）：set-url 复用 origin，二次 push 成功", async () => {
    writeFileSync(join(ws(), "a.txt"), "v1");
    const r1 = await deliverToGit(TID, remotePath, { branch: "main" });
    expect(r1.ok).toBe(true);

    // 二次：新改动，同一 remote（验证 ensureRemote set-url 路径不回归）
    writeFileSync(join(ws(), "a.txt"), "v2");
    writeFileSync(join(ws(), "b.txt"), "new");
    const r2 = await deliverToGit(TID, remotePath, { branch: "main" });
    expect(r2.ok).toBe(true);
    expect(remoteRef(remotePath, "main")).toBe(r2.commit);
    expect(r2.commit).not.toBe(r1.commit);
  });

  it("remoteUrl 不可达 → result.ok=false，message 含错误", async () => {
    writeFileSync(join(ws(), "a.txt"), "x");
    const result = await deliverToGit(TID, "/nonexistent/path/remote.git", { branch: "main" });
    expect(result.ok).toBe(false);
    expect(result.message).toBeTruthy();
  });

  it("force 选项：改写历史后 force 推送成功", async () => {
    writeFileSync(join(ws(), "a.txt"), "v1");
    await deliverToGit(TID, remotePath, { branch: "main" });

    // 改写历史
    writeFileSync(join(ws(), "a.txt"), "v1-rewritten");
    gitCli(["add", "."]);
    gitCli(["commit", "--amend", "-m", "rewritten"]);

    // 非 force（默认）应失败
    const noForce = await deliverToGit(TID, remotePath, { branch: "main" });
    expect(noForce.ok).toBe(false);

    // force 成功（amend 后无新改动，force.commit 可能为空——比对远程=本地 HEAD）
    const force = await deliverToGit(TID, remotePath, { branch: "main", force: true });
    expect(force.ok).toBe(true);
    expect(remoteRef(remotePath, "main")).toBe(gitCli(["rev-parse", "HEAD"]));
  });
});
